package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Entity;
import javax.persistence.Id;


/**
 * Aboutus generated by hbm2java
 */
@Entity
public class Aboutus implements java.io.Serializable {

	private String name;
	private String email;
	private String message;
	private String subject;

	public Aboutus() {
	}

	public Aboutus(String name, String email, String message, String subject) {
		this.name = name;
		this.email = email;
		this.message = message;
		this.subject = subject;
	}

	@Id

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Override
	public String toString() {
		return "Aboutus [name=" + name + ", email=" + email + ", message=" + message + ", subject=" + subject + "]";
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

}
