package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
	
/**
 * Bookingheader generated by hbm2java
 */
@Entity
public class Bookingheader implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int bookingid;
	private Integer phubid;
	private Integer rhubid;
	private Date startdate;
	private Date enddate;
	private Date bookingdate;
	private Integer cartypeid;
	private Integer customerid;
	private Integer fuelstatus;
	private Double addamt;
	private Double taddonrate;
	private Integer bookingdetailid;
	private String carstatus;

	public Bookingheader() {
		super();
	}

	public Bookingheader(int bookingid) {
		this.bookingid = bookingid;
	}

	public Bookingheader(int bookingid, Integer phubid, Integer rhubid, Date startdate, Date enddate, Date bookingdate,
			Integer cartypeid, Integer customerid, Integer fuelstatus, Double addamt, Double taddonrate,
			Integer bookingdetailid, String carstatus) {
		this.bookingid = bookingid;
		this.phubid = phubid;
		this.rhubid = rhubid;
		this.startdate = startdate;
		this.enddate = enddate;
		this.bookingdate = bookingdate;
		this.cartypeid = cartypeid;
		this.customerid = customerid;
		this.fuelstatus = fuelstatus;
		this.addamt = addamt;
		this.taddonrate = taddonrate;
		this.bookingdetailid = bookingdetailid;
		this.carstatus = carstatus;
	}

	public int getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(int bookingid) {
		this.bookingid = bookingid;
	}

	public Integer getPhubid() {
		return this.phubid;
	}

	public void setPhubid(Integer phubid) {
		this.phubid = phubid;
	}

	public Integer getRhubid() {
		return this.rhubid;
	}

	public void setRhubid(Integer rhubid) {
		this.rhubid = rhubid;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public Date getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(Date bookingdate) {
		this.bookingdate = bookingdate;
	}
	public Integer getCartypeid() {
		return this.cartypeid;
	}

	public void setCartypeid(Integer cartypeid) {
		this.cartypeid = cartypeid;
	}

	public Integer getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	public Integer getFuelstatus() {
		return this.fuelstatus;
	}

	public void setFuelstatus(Integer fuelstatus) {
		this.fuelstatus = fuelstatus;
	}

	public Double getAddamt() {
		return this.addamt;
	}

	public void setAddamt(Double addamt) {
		this.addamt = addamt;
	}

	public Double getTaddonrate() {
		return this.taddonrate;
	}

	public void setTaddonrate(Double taddonrate) {
		this.taddonrate = taddonrate;
	}

	public Integer getBookingdetailid() {
		return this.bookingdetailid;
	}

	public void setBookingdetailid(Integer bookingdetailid) {
		this.bookingdetailid = bookingdetailid;
	}

	public String getCarstatus() {
		return this.carstatus;
	}

	public void setCarstatus(String carstatus) {
		this.carstatus = carstatus;
	}

	@Override
	public String toString() {
		return "Bookingheader [bookingid=" + bookingid + ", phubid=" + phubid + ", rhubid=" + rhubid + ", startdate="
				+ startdate + ", enddate=" + enddate + ", bookingdate=" + bookingdate + ", cartypeid=" + cartypeid
				+ ", customerid=" + customerid + ", fuelstatus=" + fuelstatus + ", addamt=" + addamt + ", taddonrate="
				+ taddonrate + ", bookingdetailid=" + bookingdetailid + ", carstatus=" + carstatus + "]";
	}

}
