package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * Bookingdetail generated by hbm2java
 */
@Entity
public class Bookingdetail implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int bookingdetailid;
	private int addonid;
	private int bookingid;
	private int addondailyrate;

	public Bookingdetail() {
	}

	public Bookingdetail(int bookingdetailid, int addonid, int bookingid, int addondailyrate) {
		this.bookingdetailid = bookingdetailid;
		this.addonid = addonid;
		this.bookingid = bookingid;
		this.addondailyrate = addondailyrate;
	}

	
	public int getBookingdetailid() {
		return this.bookingdetailid;
	}

	public void setBookingdetailid(int bookingdetailid) {
		this.bookingdetailid = bookingdetailid;
	}


	public int getAddonid() {
		return this.addonid;
	}

	public void setAddonid(int addonid) {
		this.addonid = addonid;
	}


	public int getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(int bookingid) {
		this.bookingid = bookingid;
	}

	public int getAddondailyrate() {
		return this.addondailyrate;
	}

	@Override
	public String toString() {
		return "Bookingdetail [bookingdetailid=" + bookingdetailid + ", addonid=" + addonid + ", bookingid=" + bookingid
				+ ", addondailyrate=" + addondailyrate + "]";
	}

	public void setAddondailyrate(int addondailyrate) {
		this.addondailyrate = addondailyrate;
	}

}
