package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import java.util.Arrays;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * Cartype generated by hbm2java
 */
@Entity
public class Cartype implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int cartypeid;
	private String imagepath;
	private String cartypename;
	private Integer dailyrate;
	private Integer weeklyrate;
	private Integer monthlyrate;

	public Cartype() {
	}

	public Cartype(int cartypeid) {
		this.cartypeid = cartypeid;
	}

	public Cartype(int cartypeid, String imagepath, String cartypename, Integer dailyrate, Integer weeklyrate,
			Integer monthlyrate) {
		this.cartypeid = cartypeid;
		this.imagepath = imagepath;
		this.cartypename = cartypename;
		this.dailyrate = dailyrate;
		this.weeklyrate = weeklyrate;
		this.monthlyrate = monthlyrate;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getCartypeid() {
		return this.cartypeid;
	}

	public void setCartypeid(int cartypeid) {
		this.cartypeid = cartypeid;
	}

	public String getImagepath() {
		return this.imagepath;
	}

	public void setImagepath(String imagepath) {
		this.imagepath = imagepath;
	}

	public String getCartypename() {
		return this.cartypename;
	}

	public void setCartypename(String cartypename) {
		this.cartypename = cartypename;
	}

	public Integer getDailyrate() {
		return this.dailyrate;
	}

	public void setDailyrate(Integer dailyrate) {
		this.dailyrate = dailyrate;
	}

	public Integer getWeeklyrate() {
		return this.weeklyrate;
	}

	public void setWeeklyrate(Integer weeklyrate) {
		this.weeklyrate = weeklyrate;
	}

	public Integer getMonthlyrate() {
		return this.monthlyrate;
	}

	public void setMonthlyrate(Integer monthlyrate) {
		this.monthlyrate = monthlyrate;
	}

	@Override
	public String toString() {
		return "Cartype [cartypeid=" + cartypeid + ", imagepath=" + imagepath + ", cartypename="
				+ cartypename + ", dailyrate=" + dailyrate + ", weeklyrate=" + weeklyrate + ", monthlyrate="
				+ monthlyrate + "]";
	}

}
