package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
/**
 * City generated by hbm2java
 */

@Entity
public class City implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer cityid;
	private String cityname;
	private Integer stateid;


	public City() {
	}

	public City(String cityname) {
		this.cityname = cityname;
	}

	public City(String cityname, Integer stateid) {
		this.cityname = cityname;
		this.stateid = stateid;
	}

	
	public Integer getCityid() {
		return this.cityid;
	}

	public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	public Integer getStateid() {
		return this.stateid;
	}

	public void setStateid(Integer stateid) {
		this.stateid = stateid;
	}


	@Override
	public String toString() {
		return "City [cityid=" + cityid + ", stateid=" + stateid + ", cityname=" + cityname + "]";
	}

}
