package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Customer generated by hbm2java
 */
@Entity
public class Customer implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int customerid;
	private String fname;
	private String lname;
	private String address;
	private String email;
	private String mob1;
	private String mob2;
	private String crtype;
	private String crno;
	private String aadhar;
	private Date dob;
	private String nation;
	private String state;
	private String city;
	private String zip;
	private String dlno;
	private String dlvalidthrough;
	private String passportno;
	private String passvalidthrough;
	private String password;

	public Customer() {
	}

	public Customer(int customerid) {
		this.customerid = customerid;
	}

	public Customer(int customerid, String fname, String lname, String address, String email, String mob1, String mob2,
			String crtype, String crno, String aadhar, Date dob, String nation, String state, String city, String zip,
			String dlno, String dlvalidthrough, String passportno, String passvalidthrough, String password) {
		this.customerid = customerid;
		this.fname = fname;
		this.lname = lname;
		this.address = address;
		this.email = email;
		this.mob1 = mob1;
		this.mob2 = mob2;
		this.crtype = crtype;
		this.crno = crno;
		this.aadhar = aadhar;
		this.dob = dob;
		this.nation = nation;
		this.state = state;
		this.city = city;
		this.zip = zip;
		this.dlno = dlno;
		this.dlvalidthrough = dlvalidthrough;
		this.passportno = passportno;
		this.passvalidthrough = passvalidthrough;
		this.password = password;
	}

	
	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMob1() {
		return this.mob1;
	}

	public void setMob1(String mob1) {
		this.mob1 = mob1;
	}

	public String getMob2() {
		return this.mob2;
	}

	public void setMob2(String mob2) {
		this.mob2 = mob2;
	}

	public String getCrtype() {
		return this.crtype;
	}

	public void setCrtype(String crtype) {
		this.crtype = crtype;
	}

	public String getCrno() {
		return this.crno;
	}

	public void setCrno(String crno) {
		this.crno = crno;
	}

	public String getAadhar() {
		return this.aadhar;
	}

	public void setAadhar(String aadhar) {
		this.aadhar = aadhar;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getDlno() {
		return this.dlno;
	}

	public void setDlno(String dlno) {
		this.dlno = dlno;
	}

	public String getDlvalidthrough() {
		return this.dlvalidthrough;
	}

	public void setDlvalidthrough(String dlvalidthrough) {
		this.dlvalidthrough = dlvalidthrough;
	}

	public String getPassportno() {
		return this.passportno;
	}

	public void setPassportno(String passportno) {
		this.passportno = passportno;
	}

	public String getPassvalidthrough() {
		return this.passvalidthrough;
	}

	public void setPassvalidthrough(String passvalidthrough) {
		this.passvalidthrough = passvalidthrough;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "Customer [customerid=" + customerid + ", fname=" + fname + ", lname=" + lname + ", address=" + address
				+ ", email=" + email + ", mob1=" + mob1 + ", mob2=" + mob2 + ", crtype=" + crtype + ", crno=" + crno
				+ ", aadhar=" + aadhar + ", dob=" + dob + ", nation=" + nation + ", state=" + state + ", city=" + city
				+ ", zip=" + zip + ", dlno=" + dlno + ", dlvalidthrough=" + dlvalidthrough + ", passportno="
				+ passportno + ", passvalidthrough=" + passvalidthrough + ", password=" + password + "]";
	}

}
