package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import java.util.Arrays;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
* Hub generated by hbm2java
*/
@Entity
public class Hub implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer hubid;
	private String hubname;
	private Integer cityid;
	private Integer stateid;
	private String isAirport;
	
	public Hub() {
	}

	public Hub(String hubname, Integer cityid, Integer stateid, String isAirport) {
		this.hubname = hubname;
		this.cityid = cityid;
		this.stateid = stateid;
		this.isAirport = isAirport;
		
	}

	

	public Integer getHubid() {
		return this.hubid;
	}

	public void setHubid(Integer hubid) {
		this.hubid = hubid;
	}

	public String getHubname() {
		return this.hubname;
	}

	public void setHubname(String hubname) {
		this.hubname = hubname;
	}

	public Integer getCityid() {
		return this.cityid;
	}

	public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	public Integer getStateid() {
		return this.stateid;
	}

	public void setStateid(Integer stateid) {
		this.stateid = stateid;
	}

	public String getIsAirport() {
		return this.isAirport;
	}

	public void setIsAirport(String isAirport) {
		this.isAirport = isAirport;
	}

	@Override
	public String toString() {
		return "Hub [hubid=" + hubid + ", hubname=" + hubname + ", cityid=" + cityid + ", stateid=" + stateid
				+ ", isAirport=" + isAirport  + "]";
	}




}


