package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Invoiceheader generated by hbm2java
 */
@Entity
public class Invoiceheader implements java.io.Serializable {



	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int invoiceid;
	private Date invoicedate;
	private Integer bookingid;
	private Integer customerid;
	private String handoverdate;
	private Integer carid;
	private String returndate;
	private Double rentalamount;
	private Double totaladdonamount;
	private Double totalamount;

	public Invoiceheader() {
	}

	public Invoiceheader(int invoiceid) {
		this.invoiceid = invoiceid;
	}

	public Invoiceheader(int invoiceid, Date invoicedate, Integer bookingid, Integer customerid, String handoverdate,
			Integer carid, String returndate, Double rentalamount, Double totaladdonamount, Double totalamount) {
		this.invoiceid = invoiceid;
		this.invoicedate = invoicedate;
		this.bookingid = bookingid;
		this.customerid = customerid;
		this.handoverdate = handoverdate;
		this.carid = carid;
		this.returndate = returndate;
		this.rentalamount = rentalamount;
		this.totaladdonamount = totaladdonamount;
		this.totalamount = totalamount;
	}

	public int getInvoiceid() {
		return this.invoiceid;
	}

	public void setInvoiceid(int invoiceid) {
		this.invoiceid = invoiceid;
	}

	public Date getInvoicedate() {
		return this.invoicedate;
	}

	public void setInvoicedate(Date invoicedate) {
		this.invoicedate = invoicedate;
	}

	public Integer getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(Integer bookingid) {
		this.bookingid = bookingid;
	}

	public Integer getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	public String getHandoverdate() {
		return this.handoverdate;
	}

	public void setHandoverdate(String handoverdate) {
		this.handoverdate = handoverdate;
	}

	public Integer getCarid() {
		return this.carid;
	}

	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	public String getReturndate() {
		return this.returndate;
	}

	public void setReturndate(String returndate) {
		this.returndate = returndate;
	}

	public Double getRentalamount() {
		return this.rentalamount;
	}

	public void setRentalamount(Double rentalamount) {
		this.rentalamount = rentalamount;
	}

	public Double getTotaladdonamount() {
		return this.totaladdonamount;
	}

	public void setTotaladdonamount(Double totaladdonamount) {
		this.totaladdonamount = totaladdonamount;
	}

	public Double getTotalamount() {
		return this.totalamount;
	}

	public void setTotalamount(Double totalamount) {
		this.totalamount = totalamount;
	}

	@Override
	public String toString() {
		return "Invoiceheader [invoiceid=" + invoiceid + ", invoicedate=" + invoicedate + ", bookingid=" + bookingid
				+ ", customerid=" + customerid + ", handoverdate=" + handoverdate + ", carid=" + carid + ", returndate="
				+ returndate + ", rentalamount=" + rentalamount + ", totaladdonamount=" + totaladdonamount
				+ ", totalamount=" + totalamount + "]";
	}

}
