package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
/**
 * Login generated by hbm2java
 */
@Entity
public class Login implements java.io.Serializable {

	@Id
	
	private String name;
	private String email;
	private String password;

	public Login() {
	}

	public Login(String name, String email, String password) {
		this.name = name;
		this.email = email;
		this.password = password;
	}



	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "Login [name=" + name + ", email=" + email + ", password=" + password + "]";
	}

}
