package com.entity;
// Generated 22 Sep, 2022 6:01:12 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * State generated by hbm2java
 */
@Entity
public class State implements java.io.Serializable {


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int stateid;
	private String statename;

	public State() {
	}

	public State(int stateid, String statename) {
		this.stateid = stateid;
		this.statename = statename;
	}


	public int getStateid() {
		return this.stateid;
	}

	public void setStateid(int stateid) {
		this.stateid = stateid;
	}

	public String getStatename() {
		return this.statename;
	}

	public void setStatename(String statename) {
		this.statename = statename;
	}

	@Override
	public String toString() {
		return "State [stateid=" + stateid + ", statename=" + statename + "]";
	}



	
}
